// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Context;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("Apartment")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            Apartment = "10",
                            City = "Warszawa",
                            Number = "70b",
                            Street = "Łopuszańska",
                            ZipCode = "02-230"
                        },
                        new
                        {
                            AddressId = 2,
                            City = "Kraków",
                            Number = "15",
                            Street = "Floriańska",
                            ZipCode = "30-001"
                        },
                        new
                        {
                            AddressId = 3,
                            Apartment = "2",
                            City = "Gdańsk",
                            Number = "5",
                            Street = "Długa",
                            ZipCode = "80-001"
                        });
                });

            modelBuilder.Entity("WebApp.Models.BillingPeriod", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodId"));

                    b.Property<int>("MonthsNumber")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PeriodId");

                    b.ToTable("BillingPeriods");

                    b.HasData(
                        new
                        {
                            PeriodId = 1,
                            MonthsNumber = 1,
                            Type = "Miesięczny"
                        },
                        new
                        {
                            PeriodId = 2,
                            MonthsNumber = 12,
                            Type = "Roczny"
                        });
                });

            modelBuilder.Entity("WebApp.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("IndividualId")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("IndividualId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            IndividualId = 1
                        },
                        new
                        {
                            ClientId = 2,
                            IndividualId = 2
                        },
                        new
                        {
                            ClientId = 3,
                            CompanyId = 1
                        });
                });

            modelBuilder.Entity("WebApp.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("KrsNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PhoneNumber")
                        .HasPrecision(9)
                        .HasColumnType("decimal(9,0)");

                    b.HasKey("CompanyId");

                    b.HasIndex("AddressId");

                    b.HasIndex("KrsNumber")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            AddressId = 3,
                            Email = "kontakt@techcorp.pl",
                            KrsNumber = "0000123456",
                            Name = "TechCorp Sp. z o.o.",
                            PhoneNumber = 555666777m
                        });
                });

            modelBuilder.Entity("WebApp.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<int?>("AdditionalSupportYears")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.Property<decimal>("FullPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClientLoyal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("MaximumPaymentDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("MinimumPaymentDate")
                        .HasColumnType("date");

                    b.Property<int>("SoftVersionId")
                        .HasColumnType("int");

                    b.HasKey("ContractId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("SoftVersionId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            ContractId = 1,
                            AdditionalSupportYears = 0,
                            ClientId = 1,
                            FullPrice = 5000.00m,
                            IsActive = true,
                            IsClientLoyal = false,
                            IsPaid = true,
                            MaximumPaymentDate = new DateOnly(2026, 6, 14),
                            MinimumPaymentDate = new DateOnly(2026, 6, 1),
                            SoftVersionId = 2
                        },
                        new
                        {
                            ContractId = 2,
                            AdditionalSupportYears = 2,
                            ClientId = 3,
                            DiscountId = 2,
                            FullPrice = 14000.00m,
                            IsActive = true,
                            IsClientLoyal = true,
                            IsPaid = false,
                            MaximumPaymentDate = new DateOnly(2026, 6, 25),
                            MinimumPaymentDate = new DateOnly(2026, 6, 5),
                            SoftVersionId = 3
                        });
                });

            modelBuilder.Entity("WebApp.Models.ContractPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("bit");

                    b.HasKey("PaymentId");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractPayments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 5000.00m,
                            ContractId = 1,
                            CreatedAt = new DateTime(2026, 6, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRefunded = false
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 4000.00m,
                            ContractId = 2,
                            CreatedAt = new DateTime(2026, 6, 10, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            IsRefunded = false
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 4000.00m,
                            ContractId = 2,
                            CreatedAt = new DateTime(2026, 6, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRefunded = false
                        });
                });

            modelBuilder.Entity("WebApp.Models.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"));

                    b.Property<int>("DiscountTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(3)
                        .HasColumnType("decimal(3,0)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DiscountId");

                    b.HasIndex("DiscountTypeId");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            DiscountId = 1,
                            DiscountTypeId = 1,
                            EndDate = new DateTime(2026, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Black Friday 2026",
                            Percentage = 20.0m,
                            StartDate = new DateTime(2026, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DiscountId = 2,
                            DiscountTypeId = 2,
                            EndDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wiosna 2026",
                            Percentage = 10.0m,
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebApp.Models.DiscountType", b =>
                {
                    b.Property<int>("DiscountTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountTypeId"));

                    b.Property<string>("Offer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DiscountTypeId");

                    b.ToTable("DiscountTypes");

                    b.HasData(
                        new
                        {
                            DiscountTypeId = 1,
                            Offer = "Black Friday"
                        },
                        new
                        {
                            DiscountTypeId = 2,
                            Offer = "Promocja Wiosenna"
                        });
                });

            modelBuilder.Entity("WebApp.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Login = "admin",
                            Password = "AQAAAAIAAYagAAAAECOSfrReTZmf3D5jx4FjggFLBBHDyiSjXoaa7e9vIynzts02MN1zw4/kahgjiiALYw==",
                            RoleId = 1
                        },
                        new
                        {
                            EmployeeId = 2,
                            Login = "j.kowalski",
                            Password = "AQAAAAIAAYagAAAAEFFuLGR1ug884ZyX58kcSf1aQ6HCt5fF/yNY1g2g9E6SqPkDmVCR/7ItPJGJFupO9g==",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("WebApp.Models.Individual", b =>
                {
                    b.Property<int>("IndividualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndividualId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<decimal>("PhoneNumber")
                        .HasPrecision(9)
                        .HasColumnType("decimal(9,0)");

                    b.HasKey("IndividualId");

                    b.HasIndex("AddressId");

                    b.HasIndex("Pesel")
                        .IsUnique();

                    b.ToTable("Individuals");

                    b.HasData(
                        new
                        {
                            IndividualId = 1,
                            AddressId = 1,
                            Email = "jan.kowalski@wp.pl",
                            FirstName = "Jan",
                            IsActive = true,
                            LastName = "Kowalski",
                            Pesel = "90010112345",
                            PhoneNumber = 123456789m
                        },
                        new
                        {
                            IndividualId = 2,
                            AddressId = 2,
                            Email = "anna.nowak@gmail.com",
                            FirstName = "Anna",
                            IsActive = true,
                            LastName = "Nowak",
                            Pesel = "95050554321",
                            PhoneNumber = 987654321m
                        });
                });

            modelBuilder.Entity("WebApp.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Pracownik"
                        });
                });

            modelBuilder.Entity("WebApp.Models.SoftCategory", b =>
                {
                    b.Property<int>("SoftCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SoftCategoryId");

                    b.ToTable("SoftCategories");

                    b.HasData(
                        new
                        {
                            SoftCategoryId = 1,
                            Name = "Finanse i Księgowość"
                        },
                        new
                        {
                            SoftCategoryId = 2,
                            Name = "Edukacja"
                        });
                });

            modelBuilder.Entity("WebApp.Models.SoftVersion", b =>
                {
                    b.Property<int>("SoftVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftVersionId"));

                    b.Property<bool>("IsNewest")
                        .HasColumnType("bit");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("SoftVersionId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("SoftVersions");

                    b.HasData(
                        new
                        {
                            SoftVersionId = 1,
                            IsNewest = false,
                            SoftwareId = 1,
                            VersionNumber = "1.0"
                        },
                        new
                        {
                            SoftVersionId = 2,
                            IsNewest = true,
                            SoftwareId = 1,
                            VersionNumber = "2.0"
                        },
                        new
                        {
                            SoftVersionId = 3,
                            IsNewest = true,
                            SoftwareId = 2,
                            VersionNumber = "1.5"
                        });
                });

            modelBuilder.Entity("WebApp.Models.Software", b =>
                {
                    b.Property<int>("SoftwareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftwareId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LicensePricePerYear")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoftCategoryId")
                        .HasColumnType("int");

                    b.HasKey("SoftwareId");

                    b.HasIndex("SoftCategoryId");

                    b.ToTable("Software");

                    b.HasData(
                        new
                        {
                            SoftwareId = 1,
                            Description = "System do pełnej księgowości.",
                            LicensePricePerYear = 5000.00m,
                            Name = "Księgowość Pro",
                            SoftCategoryId = 1
                        },
                        new
                        {
                            SoftwareId = 2,
                            Description = "Zarządzanie uczelnią wyższą.",
                            LicensePricePerYear = 12000.00m,
                            Name = "EduPlatform",
                            SoftCategoryId = 2
                        });
                });

            modelBuilder.Entity("WebApp.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<int>("BillingPeriodId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClientLoyal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PeriodPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SoftVersionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("BillingPeriodId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("SoftVersionId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            SubscriptionId = 1,
                            BillingPeriodId = 1,
                            ClientId = 2,
                            EndDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsClientLoyal = false,
                            Name = "Subskrypcja Księgowość Standard",
                            PeriodPrice = 500.00m,
                            SoftVersionId = 1,
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SubscriptionId = 2,
                            BillingPeriodId = 2,
                            ClientId = 3,
                            DiscountId = 2,
                            EndDate = new DateTime(2027, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsClientLoyal = true,
                            Name = "Subskrypcja EduPlatform Premium",
                            PeriodPrice = 10000.00m,
                            SoftVersionId = 3,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebApp.Models.SubscriptionPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionPayments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 500.00m,
                            PaymentDate = new DateTime(2026, 6, 1, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 1
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 10000.00m,
                            PaymentDate = new DateTime(2025, 5, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 2
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 9500.00m,
                            PaymentDate = new DateTime(2026, 5, 9, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 2
                        });
                });

            modelBuilder.Entity("WebApp.Models.Client", b =>
                {
                    b.HasOne("WebApp.Models.Company", "Company")
                        .WithMany("Client")
                        .HasForeignKey("CompanyId");

                    b.HasOne("WebApp.Models.Individual", "Individual")
                        .WithMany("Client")
                        .HasForeignKey("IndividualId");

                    b.Navigation("Company");

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("WebApp.Models.Company", b =>
                {
                    b.HasOne("WebApp.Models.Address", "Address")
                        .WithMany("CompanyClients")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("WebApp.Models.Contract", b =>
                {
                    b.HasOne("WebApp.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Discount", "Discount")
                        .WithMany("Contracts")
                        .HasForeignKey("DiscountId");

                    b.HasOne("WebApp.Models.SoftVersion", "SoftVersion")
                        .WithMany("Contracts")
                        .HasForeignKey("SoftVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Discount");

                    b.Navigation("SoftVersion");
                });

            modelBuilder.Entity("WebApp.Models.ContractPayment", b =>
                {
                    b.HasOne("WebApp.Models.Contract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("WebApp.Models.Discount", b =>
                {
                    b.HasOne("WebApp.Models.DiscountType", "DiscountType")
                        .WithMany("Discounts")
                        .HasForeignKey("DiscountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscountType");
                });

            modelBuilder.Entity("WebApp.Models.Employee", b =>
                {
                    b.HasOne("WebApp.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebApp.Models.Individual", b =>
                {
                    b.HasOne("WebApp.Models.Address", "Address")
                        .WithMany("IndividualClients")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("WebApp.Models.SoftVersion", b =>
                {
                    b.HasOne("WebApp.Models.Software", "Software")
                        .WithMany("SoftVersions")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Software");
                });

            modelBuilder.Entity("WebApp.Models.Software", b =>
                {
                    b.HasOne("WebApp.Models.SoftCategory", "SoftCategory")
                        .WithMany("Softwares")
                        .HasForeignKey("SoftCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoftCategory");
                });

            modelBuilder.Entity("WebApp.Models.Subscription", b =>
                {
                    b.HasOne("WebApp.Models.BillingPeriod", "BillingPeriod")
                        .WithMany("Subscriptions")
                        .HasForeignKey("BillingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Client", "Client")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Discount", "Discount")
                        .WithMany("Subscriptions")
                        .HasForeignKey("DiscountId");

                    b.HasOne("WebApp.Models.SoftVersion", "SoftVersion")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SoftVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingPeriod");

                    b.Navigation("Client");

                    b.Navigation("Discount");

                    b.Navigation("SoftVersion");
                });

            modelBuilder.Entity("WebApp.Models.SubscriptionPayment", b =>
                {
                    b.HasOne("WebApp.Models.Subscription", "Subscription")
                        .WithMany("SubscriptionPayments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("WebApp.Models.Address", b =>
                {
                    b.Navigation("CompanyClients");

                    b.Navigation("IndividualClients");
                });

            modelBuilder.Entity("WebApp.Models.BillingPeriod", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("WebApp.Models.Client", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("WebApp.Models.Company", b =>
                {
                    b.Navigation("Client");
                });

            modelBuilder.Entity("WebApp.Models.Contract", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WebApp.Models.Discount", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("WebApp.Models.DiscountType", b =>
                {
                    b.Navigation("Discounts");
                });

            modelBuilder.Entity("WebApp.Models.Individual", b =>
                {
                    b.Navigation("Client");
                });

            modelBuilder.Entity("WebApp.Models.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("WebApp.Models.SoftCategory", b =>
                {
                    b.Navigation("Softwares");
                });

            modelBuilder.Entity("WebApp.Models.SoftVersion", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("WebApp.Models.Software", b =>
                {
                    b.Navigation("SoftVersions");
                });

            modelBuilder.Entity("WebApp.Models.Subscription", b =>
                {
                    b.Navigation("SubscriptionPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
